import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const dirs = ["src", "public"];
const files = [];

function exists(p) {
  try {
    statSync(p);
    return true;
  } catch {
    return false;
  }
}

function walk(p) {
  const st = statSync(p);
  if (st.isDirectory()) {
    for (const e of readdirSync(p)) {
      if (e === "node_modules" || e === "dist" || e === ".git") continue;
      walk(join(p, e));
    }
  } else if (/\.(ts|astro|css|json|svg)$/.test(p)) {
    files.push(p);
  }
}
for (const d of dirs) {
  if (exists(d)) walk(d);
}
if (exists(join(root, "astro.config.mjs"))) files.push(join(root, "astro.config.mjs"));

const bad = [
  { re: /(^|\s)\/\//, label: "// comment" },
  { re: /(^|\s)\/\*/, label: "/* comment" },
  { re: /—/, label: "em-dash" },
  { re: /TODO|FIXME/i, label: "TODO/FIXME" },
  { re: /generated by|made by|created by/i, label: "AI signature" },
  { re: /[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE0F}]/u, label: "emoji" },
];

let failed = false;
for (const f of files) {
  const content = readFileSync(f, "utf8");
  const lines = content.split(/\r?\n/);
  lines.forEach((line, i) => {
    for (const b of bad) {
      if (b.re.test(line)) {
        console.log(`[${b.label}] ${f}:${i + 1}  ${line.trim()}`);
        failed = true;
      }
    }
  });
}
if (failed) {
  process.exit(1);
} else {
  console.log("hygiene: clean");
}
